### ISSUE TITLE
How can I run tests?

### ISSUE THREAD

**Issue by uchan-nos** [icoxfog417/pykintone#22]
I need to write and run tests because I want to fix a bug.
(The bug is inside kintoneService.app method.)

To run tests, I executed the following commands:

    cd pykintone
    python3 -m unittest

Then I got a lot of errors, which say "FileNotFoundError: [Errno 2] No such file or directory: '/path/to/pykintone/tests/../account.yaml'".

Could you please tell me a right way to run tests.

**Comment by icoxfog417** [comment]
Thank you for your contribution! To access the kintone, `account.yaml` have to locate on pykintone root folder. And you can create kintone APP for test by `pykintoneTest.zip` on you kintone environment.

**Comment by uchan-nos** [comment]
Thanks. I'll try to run tests.

**Comment by uchan-nos** [comment]
memo:
Tests were failed.

I did the following procedure:
1. Create an application using pykintoneTest.zip
2. Create an account.yaml such as:
    ```
    domain: my-domain
    apps:
        test:
            id: 75
            token: ...
    ```
3. Execute `python3 -m unittest`

I got the following results.

```
$ python3 -m unittest
EEEEEYou have to delete the application from the application administration view.
EEEEYou have to delete the application from the application administration view.
EFYou have to delete the application from the application administration view.
EEYou have to delete the application from the application administration view.
domain:  test_domain
login:    /
basic:    /
.E....EEEEEEEEEEEECaution, gruop deserialization is not checked. Please make user who belongs to some group.
.FCaution, organization and title deserialization is not checked. Please make user who belongs to some organization.
.
======================================================================
ERROR: test_copy_application (tests.application_settings.test_administrator.TestGeneral)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/uchan/workspace/github.com/uchan-nos/pykintone/tests/application_settings/test_administrator.py", line 55, in test_copy_application
    app = kintone.app()
  File "/mnt/c/Users/uchan/workspace/github.com/uchan-nos/pykintone/pykintone/account.py", line 120, in app
    if len(existed) > 0:
UnboundLocalError: local variable 'existed' referenced before assignment

...
----------------------------------------------------------------------
Ran 34 tests in 1.289s

FAILED (failures=2, errors=25)
```

**Comment by uchan-nos** [comment]
I've got different results when I checked out master branch and ran the tests.

```
$ python3 -m unittest
EEEFFYou have to delete the application from the application administration view.
FFFFYou have to delete the application from the application administration view.
EFYou have to delete the application from the application administration view.
FFYou have to delete the application from the application administration view.
domain:  test_domain
login:    /
basic:    /
.domain:         my-domain
login:    /
basic:    /
app:
  id=75, token=...
...F.FEFFFFFFF.Caution, gruop deserialization is not checked. Please make user who belongs to some group.
.FCaution, organization and title deserialization is not checked. Please make user who belongs to some organization.
.
======================================================================
ERROR: test_copy_application (tests.application_settings.test_administrator.TestGeneral)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/uchan/workspace/github.com/uchan-nos/pykintone/tests/application_settings/test_administrator.py", line 58, in test_copy_application
    created = admin.copy_application("copied application", app.app_id)
  File "/mnt/c/Users/uchan/workspace/github.com/uchan-nos/pykintone/pykintone/application_settings/administrator.py", line 133, in copy_application
    raise Exception("Error is occurred when getting the application settings.")
Exception: Error is occurred when getting the application settings.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/uchan/workspace/github.com/uchan-nos/pykintone/tests/application_settings/test_administrator.py", line 59, in test_copy_application
    self.assertTrue(created.ok)
  File "/mnt/c/Users/uchan/workspace/github.com/uchan-nos/pykintone/pykintone/application_settings/base_administration_api.py", line 28, in __exit__
    raise Exception("There are some changes to be committed, but no application id.")
Exception: There are some changes to be committed, but no application id.

...
----------------------------------------------------------------------
Ran 32 tests in 4.251s

FAILED (failures=19, errors=5)
```

**Comment by icoxfog417** [comment]
To run the application test (application creation etc), kintone user has to have administrative authority.
The application token doesn't allow this authority. So if you run all tests, you have to prepare the user that has administrative authority.

**Comment by nishio** [comment]
With administrative authority, I got an error and 3 failures:
```
======================================================================
ERROR: test_user_organization_titles (tests.user_api.test_export.TestExport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nishio/upload_books/foo/pykintone/tests/user_api/test_export.py", line 22, in test_user_organization_titles
    ots_result = export_api.get_user_organization_titles(code)
  File "/home/nishio/upload_books/foo/pykintone/pykintone/user_api/export.py", line 35, in get_user_organization_titles
    r = ur.UserOrganizationTitlesResult(resp)
  File "/home/nishio/upload_books/foo/pykintone/pykintone/user_api/user_api_result.py", line 34, in __init__
    t = Title.deserialize(ot["title"])
  File "/home/nishio/upload_books/foo/pykintone/pykintone/structure.py", line 32, in deserialize
    return cls._deserialize(json_body, lambda f: (f, ""))
  File "/home/nishio/upload_books/foo/pykintone/pykintone/structure.py", line 51, in _deserialize
    for k in json_body:
TypeError: 'NoneType' object is not iterable

======================================================================
FAIL: test_datetime_to_value (tests.test_account.TestService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nishio/upload_books/foo/pykintone/tests/test_account.py", line 37, in test_datetime_to_value
    self.assertEqual(utc, utced)
AssertionError: '2017-12-21T09:51:50Z' != '2017-12-21T09:32:50Z'
- 2017-12-21T09:51:50Z
?               ^^
+ 2017-12-21T09:32:50Z
?               ^^


======================================================================
FAIL: test_options (tests.test_app.TestApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nishio/upload_books/foo/pykintone/tests/test_app.py", line 169, in test_options
    self.assertTrue(len(result.records) > 0)
AssertionError: False is not true

======================================================================
FAIL: test_process (tests.test_app.TestApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nishio/upload_books/foo/pykintone/tests/test_app.py", line 160, in test_process
    self.assertTrue(proceeded.ok)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 32 tests in 36.059s

FAILED (failures=3, errors=1)
```

**Comment by nishio** [comment]
(when I used API token, it was FAILED (failures=20, errors=5))

**Comment by uchan-nos** [comment]
Anyway, I could get to know hot to run tests. Thank you.
I'll close this issue, and open new issue addressing test errors.
