### ISSUE TITLE
Failed to deserialize user's organization if he has no job title

### ISSUE THREAD

**Issue by uchan-nos** [icoxfog417/pykintone#28]
If an user has no job title (see attached image), one test fails:

```
$ python3 -m unittest tests/user_api/test_export.py
Caution, gruop deserialization is not checked. Please make user who belongs to some group.
..E
======================================================================
ERROR: test_user_organization_titles (tests.user_api.test_export.TestExport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/uchan/workspace/github.com/uchan-nos/pykintone/tests/user_api/test_export.py", line 22, in test_user_organization_titles
    ots_result = export_api.get_user_organization_titles(code)
  File "/mnt/c/Users/uchan/workspace/github.com/uchan-nos/pykintone/pykintone/user_api/export.py", line 35, in get_user_organization_titles
    r = ur.UserOrganizationTitlesResult(resp)
  File "/mnt/c/Users/uchan/workspace/github.com/uchan-nos/pykintone/pykintone/user_api/user_api_result.py", line 34, in __init__
    t = Title.deserialize(ot["title"])
  File "/mnt/c/Users/uchan/workspace/github.com/uchan-nos/pykintone/pykintone/structure.py", line 32, in deserialize
    return cls._deserialize(json_body, lambda f: (f, ""))
  File "/mnt/c/Users/uchan/workspace/github.com/uchan-nos/pykintone/pykintone/structure.py", line 51, in _deserialize
    for k in json_body:
TypeError: 'NoneType' object is not iterable

----------------------------------------------------------------------
Ran 3 tests in 0.908s

FAILED (errors=1)
```

This is because the following line tries to deserialize `ot["title"]` although it is None.

https://github.com/icoxfog417/pykintone/blob/ecca394b24105004f3372a22efb205c32bcf52bf/pykintone/user_api/user_api_result.py#L34

This test passes if I set a job title to the user.

**Comment by uchan-nos** [comment]
![no_job_title](https://user-images.githubusercontent.com/1825663/34323967-e5525ef0-e8a1-11e7-9831-be79a8cbc947.png)

**Comment by uchan-nos** [comment]
I publish a pull requests which fixes this bug.
I confirmed that failed tests are not increased by this fix.
Could you please merge it?

**Comment by icoxfog417** [comment]
Thank you for your Pull Request! To add the description about test to README is really helpful.
I added some reviews to your PR. Could you please confirm these?

**Comment by uchan-nos** [comment]
Thank you reviewing! I answered!
